import dotenv from "dotenv";
import { promises as fs } from "node:fs";
import path from "node:path";
import { PrismaMariaDb } from "@prisma/adapter-mariadb";
import { PrismaClient } from "../src/generated/prisma/client";
import {
  CoralProfileStatus,
  ExchangeKind,
  ExchangeVisibility,
  TradeCoralEventHandoffStatus,
  TradeCoralSide,
  TradeStatus,
} from "../src/generated/prisma/enums";

dotenv.config({ path: ".env" });
if (process.env.NODE_ENV !== "production") {
  dotenv.config({ path: ".env.development" });
}
dotenv.config({ path: ".env.local" });

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  console.error("DATABASE_URL is not set; cannot run scenario seed.");
  process.exit(1);
}

const prisma = new PrismaClient({
  adapter: new PrismaMariaDb(databaseUrl),
});

const RUN_STAMP = new Date().toISOString().replace(/[-:.TZ]/g, "").slice(0, 14);
const MOCK_PREFIX = `mock-scn-${RUN_STAMP}`;
const EXCHANGE_COUNT_PER_KIND = 5;
const HOBBYISTS_PER_EXCHANGE = 10;
const LISTING_WINDOW_DAYS = 90;

type SeededHobbyistSummary = {
  userId: string;
  email: string;
  coralsCreated: number;
  tradesInitiated: number;
  tradesCompleted: number;
  tradesExpired: number;
};

type SeededExchangeSummary = {
  exchangeId: string;
  exchangeName: string;
  kind: ExchangeKind;
  hobbyistCount: number;
  coralCount: number;
  activeListingsCount: number;
  tradesInitiatedCount: number;
  tradesCompletedCount: number;
  tradesExpiredCount: number;
  hobbyists: SeededHobbyistSummary[];
};

function randomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function pickOne<T>(arr: T[]): T | null {
  if (arr.length === 0) {
    return null;
  }
  return arr[randomInt(0, arr.length - 1)];
}

function sampleWithoutReplacement<T>(arr: T[], count: number): T[] {
  const copy = [...arr];
  const selected: T[] = [];
  const n = Math.min(count, copy.length);
  for (let i = 0; i < n; i += 1) {
    const idx = randomInt(0, copy.length - 1);
    selected.push(copy[idx]);
    copy.splice(idx, 1);
  }
  return selected;
}

function plusDays(d: Date, days: number) {
  return new Date(d.getTime() + days * 24 * 60 * 60 * 1000);
}

async function createExchangeWithMembers(kind: ExchangeKind, index: number) {
  const adminEmail = `${MOCK_PREFIX}.${kind.toLowerCase()}.${index}.owner@example.test`;
  const admin = await prisma.user.create({
    data: {
      email: adminEmail,
      alias: `${kind === ExchangeKind.EVENT ? "Event" : "Group"} Host ${index + 1}`,
    },
  });

  const exchange = await prisma.exchange.create({
    data: {
      name:
        kind === ExchangeKind.EVENT
          ? `Scenario Event ${index + 1} (${RUN_STAMP})`
          : `Scenario Group ${index + 1} (${RUN_STAMP})`,
      description: `Mock scenario exchange generated by ${MOCK_PREFIX}.`,
      kind,
      visibility: ExchangeVisibility.PUBLIC,
      eventDate: kind === ExchangeKind.EVENT ? plusDays(new Date(), 7 + index) : null,
      createdById: admin.id,
      memberships: {
        create: { userId: admin.id },
      },
    },
  });

  const hobbyists = [];
  for (let i = 0; i < HOBBYISTS_PER_EXCHANGE; i += 1) {
    const user = await prisma.user.create({
      data: {
        email: `${MOCK_PREFIX}.${kind.toLowerCase()}.${index}.h${i + 1}@example.test`,
        alias: `Hobbyist ${i + 1}`,
      },
    });

    await prisma.exchangeMembership.create({
      data: {
        exchangeId: exchange.id,
        userId: user.id,
      },
    });
    hobbyists.push(user);
  }

  return { exchange, hobbyists };
}

async function seedExchangeData(
  exchange: { id: string; name: string; kind: ExchangeKind },
  hobbyists: { id: string; email: string }[],
): Promise<SeededExchangeSummary> {
  const now = new Date();
  const activeListingExpiresAt = plusDays(now, LISTING_WINDOW_DAYS);
  const exchangeCoralPoolByUser = new Map<string, string[]>();

  const hobbyistSummaries: SeededHobbyistSummary[] = hobbyists.map((h) => ({
    userId: h.id,
    email: h.email,
    coralsCreated: 0,
    tradesInitiated: 0,
    tradesCompleted: 0,
    tradesExpired: 0,
  }));
  const hobbyistSummaryByUserId = new Map(hobbyistSummaries.map((s) => [s.userId, s]));

  for (const hobbyist of hobbyists) {
    const coralCount = randomInt(0, 3);
    const coralIds: string[] = [];
    for (let i = 0; i < coralCount; i += 1) {
      const coral = await prisma.coral.create({
        data: {
          userId: hobbyist.id,
          name: `Mock Coral ${i + 1} (${hobbyist.email.split("@")[0]})`,
          description: `Generated by ${MOCK_PREFIX} for scenario testing.`,
          profileStatus: CoralProfileStatus.UNLISTED,
        },
      });
      coralIds.push(coral.id);

      await prisma.exchangeListing.create({
        data: {
          exchangeId: exchange.id,
          coralId: coral.id,
          expiresAt: activeListingExpiresAt,
        },
      });
    }
    exchangeCoralPoolByUser.set(hobbyist.id, coralIds);
    const summary = hobbyistSummaryByUserId.get(hobbyist.id);
    if (summary) {
      summary.coralsCreated += coralIds.length;
    }
  }

  const createTrade = async (opts: {
    initiatorUserId: string;
    peerUserId: string;
    status: TradeStatus;
    expiresAt: Date;
  }) => {
    const initiatorCorals = exchangeCoralPoolByUser.get(opts.initiatorUserId) ?? [];
    const peerCorals = exchangeCoralPoolByUser.get(opts.peerUserId) ?? [];
    if (initiatorCorals.length === 0 || peerCorals.length === 0) {
      return null;
    }

    const initiatorCoralId = pickOne(initiatorCorals);
    const peerCoralId = pickOne(peerCorals);
    if (!initiatorCoralId || !peerCoralId) {
      return null;
    }

    const trade = await prisma.trade.create({
      data: {
        exchangeId: exchange.id,
        initiatorUserId: opts.initiatorUserId,
        peerUserId: opts.peerUserId,
        status: opts.status,
        expiresAt: opts.expiresAt,
        corals: {
          create: [
            { coralId: initiatorCoralId, side: TradeCoralSide.INITIATOR },
            { coralId: peerCoralId, side: TradeCoralSide.PEER },
          ],
        },
      },
      include: { corals: true },
    });

    if (opts.status === TradeStatus.APPROVED) {
      const coralIds = trade.corals.map((c) => c.coralId);

      await prisma.exchangeListing.deleteMany({
        where: { coralId: { in: coralIds } },
      });
      await prisma.coral.updateMany({
        where: { id: { in: coralIds } },
        data: { profileStatus: CoralProfileStatus.TRADED },
      });
      if (exchange.kind === ExchangeKind.EVENT) {
        await prisma.tradeCoral.updateMany({
          where: { tradeId: trade.id },
          data: { eventHandoffStatus: TradeCoralEventHandoffStatus.AWAITING_CHECKIN },
        });
      }

      for (const userId of [opts.initiatorUserId, opts.peerUserId]) {
        const arr = exchangeCoralPoolByUser.get(userId) ?? [];
        const filtered = arr.filter((id) => !coralIds.includes(id));
        exchangeCoralPoolByUser.set(userId, filtered);
      }
    }

    return trade.id;
  };

  let exchangeTradesInitiated = 0;
  let exchangeTradesCompleted = 0;
  let exchangeTradesExpired = 0;

  for (const hobbyist of hobbyists) {
    const summary = hobbyistSummaryByUserId.get(hobbyist.id);
    if (!summary) {
      continue;
    }

    const initiatedTarget = randomInt(0, 3);
    const completedTarget = randomInt(0, 1);
    const expiredTarget = randomInt(0, 1);

    const peers = hobbyists.filter((h) => h.id !== hobbyist.id);

    for (let i = 0; i < initiatedTarget; i += 1) {
      const peer = pickOne(peers);
      if (!peer) {
        continue;
      }
      const created = await createTrade({
        initiatorUserId: hobbyist.id,
        peerUserId: peer.id,
        status: TradeStatus.OFFER,
        expiresAt: plusDays(now, randomInt(1, 21)),
      });
      if (created) {
        summary.tradesInitiated += 1;
        exchangeTradesInitiated += 1;
      }
    }

    for (let i = 0; i < completedTarget; i += 1) {
      const peersWithCorals = sampleWithoutReplacement(
        peers.filter((p) => (exchangeCoralPoolByUser.get(p.id) ?? []).length > 0),
        peers.length,
      );
      const peer = peersWithCorals[0];
      if (!peer) {
        continue;
      }
      const created = await createTrade({
        initiatorUserId: hobbyist.id,
        peerUserId: peer.id,
        status: TradeStatus.APPROVED,
        expiresAt: plusDays(now, randomInt(1, 14)),
      });
      if (created) {
        summary.tradesCompleted += 1;
        exchangeTradesCompleted += 1;
      }
    }

    for (let i = 0; i < expiredTarget; i += 1) {
      const peer = pickOne(peers);
      if (!peer) {
        continue;
      }
      const created = await createTrade({
        initiatorUserId: hobbyist.id,
        peerUserId: peer.id,
        status: TradeStatus.EXPIRED,
        expiresAt: plusDays(now, -randomInt(1, 7)),
      });
      if (created) {
        summary.tradesExpired += 1;
        exchangeTradesExpired += 1;
      }
    }
  }

  const activeListingsCount = await prisma.exchangeListing.count({
    where: {
      exchangeId: exchange.id,
      expiresAt: { gt: now },
    },
  });

  return {
    exchangeId: exchange.id,
    exchangeName: exchange.name,
    kind: exchange.kind,
    hobbyistCount: hobbyists.length,
    coralCount: hobbyistSummaries.reduce((sum, h) => sum + h.coralsCreated, 0),
    activeListingsCount,
    tradesInitiatedCount: exchangeTradesInitiated,
    tradesCompletedCount: exchangeTradesCompleted,
    tradesExpiredCount: exchangeTradesExpired,
    hobbyists: hobbyistSummaries,
  };
}

function buildReadmeContent(summary: {
  runStamp: string;
  prefix: string;
  exchanges: SeededExchangeSummary[];
}) {
  const eventCount = summary.exchanges.filter((e) => e.kind === ExchangeKind.EVENT).length;
  const groupCount = summary.exchanges.filter((e) => e.kind === ExchangeKind.GROUP).length;
  const hobbyistCount = summary.exchanges.reduce((sum, e) => sum + e.hobbyistCount, 0);
  const coralCount = summary.exchanges.reduce((sum, e) => sum + e.coralCount, 0);
  const listings = summary.exchanges.reduce((sum, e) => sum + e.activeListingsCount, 0);
  const initiated = summary.exchanges.reduce((sum, e) => sum + e.tradesInitiatedCount, 0);
  const completed = summary.exchanges.reduce((sum, e) => sum + e.tradesCompletedCount, 0);
  const expired = summary.exchanges.reduce((sum, e) => sum + e.tradesExpiredCount, 0);

  const lines: string[] = [];
  lines.push("# Scenario Seed Report");
  lines.push("");
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push(`Run tag: \`${summary.prefix}\``);
  lines.push("");
  lines.push("## Requested Configuration");
  lines.push("");
  lines.push("- Exchanges: 10 total (5 EVENT / 5 GROUP)");
  lines.push("- Hobbyists: 10 per exchange");
  lines.push("- Corals: random 0-3 per hobbyist");
  lines.push("- Trades per hobbyist: 0-3 initiated, 0-1 completed, 0-1 expired");
  lines.push("");
  lines.push("## Seed Totals");
  lines.push("");
  lines.push(`- Exchanges created: ${summary.exchanges.length} (EVENT ${eventCount} / GROUP ${groupCount})`);
  lines.push(`- Hobbyist memberships created: ${hobbyistCount}`);
  lines.push(`- Corals created: ${coralCount}`);
  lines.push(`- Active listings now present: ${listings}`);
  lines.push(`- Trades created: initiated/OFFER ${initiated}, completed/APPROVED ${completed}, expired/EXPIRED ${expired}`);
  lines.push("");
  lines.push("## Per-Exchange Summary");
  lines.push("");

  for (const exchange of summary.exchanges) {
    lines.push(`### ${exchange.exchangeName}`);
    lines.push("");
    lines.push(`- ID: \`${exchange.exchangeId}\``);
    lines.push(`- Kind: ${exchange.kind}`);
    lines.push(`- Hobbyists: ${exchange.hobbyistCount}`);
    lines.push(`- Corals created: ${exchange.coralCount}`);
    lines.push(`- Active listings: ${exchange.activeListingsCount}`);
    lines.push(
      `- Trades: initiated/OFFER ${exchange.tradesInitiatedCount}, completed/APPROVED ${exchange.tradesCompletedCount}, expired/EXPIRED ${exchange.tradesExpiredCount}`,
    );
    lines.push("");
    lines.push("| Hobbyist | Corals | Initiated | Completed | Expired |");
    lines.push("|---|---:|---:|---:|---:|");
    for (const h of exchange.hobbyists) {
      lines.push(
        `| ${h.email} | ${h.coralsCreated} | ${h.tradesInitiated} | ${h.tradesCompleted} | ${h.tradesExpired} |`,
      );
    }
    lines.push("");
  }

  lines.push("## Notes");
  lines.push("");
  lines.push("- This script runs in append mode and does not delete existing data.");
  lines.push("- Names and emails are namespaced by run tag to avoid collisions.");
  lines.push("- Completed trades mark traded corals as `TRADED` and remove their listings.");
  lines.push(`- Source run stamp: ${summary.runStamp}`);
  lines.push("");

  return `${lines.join("\n")}\n`;
}

async function main() {
  const seededExchanges: SeededExchangeSummary[] = [];

  for (let i = 0; i < EXCHANGE_COUNT_PER_KIND; i += 1) {
    const { exchange, hobbyists } = await createExchangeWithMembers(ExchangeKind.EVENT, i);
    const seeded = await seedExchangeData(exchange, hobbyists);
    seededExchanges.push(seeded);
  }

  for (let i = 0; i < EXCHANGE_COUNT_PER_KIND; i += 1) {
    const { exchange, hobbyists } = await createExchangeWithMembers(ExchangeKind.GROUP, i);
    const seeded = await seedExchangeData(exchange, hobbyists);
    seededExchanges.push(seeded);
  }

  const readme = buildReadmeContent({
    runStamp: RUN_STAMP,
    prefix: MOCK_PREFIX,
    exchanges: seededExchanges,
  });
  const outPath = path.resolve(process.cwd(), "README-SEED.md");
  await fs.writeFile(outPath, readme, "utf8");

  console.log(`Scenario seed complete (${MOCK_PREFIX}).`);
  console.log(`Report written to ${outPath}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
